// Regenerated by scripts/write-build-meta.mjs during CI builds.
export const BUILD_COMMIT = "ce5baf7a480a5be31fbeb430d616ee05b09412b7";
export const BUILD_BRANCH = "main";
export const BUILD_SOURCE = "github-actions";
