// Regenerated by scripts/write-build-meta.mjs during CI builds.
export const BUILD_COMMIT = "d1c02b49e84e1c13a3116d47645660d91da963a8";
export const BUILD_BRANCH = "main";
export const BUILD_SOURCE = "github-actions";
