// Regenerated by scripts/write-build-meta.mjs during CI builds.
export const BUILD_COMMIT = "812a066f6b0d0ecbfd788e2e60e534ba78d41290";
export const BUILD_BRANCH = "main";
export const BUILD_SOURCE = "github-actions";
